// Button-04826

import { Injectable } from '@angular/core'

import { Action } from '@core/components/actions/action.default'
/**
 * @deprecated
 * In the upcoming release, this file will be deleted. If you have any custom code in this file, please move it to the effects file.
 * Service that handles the `create` action
 * This service is auto generated by `UI Studio` tool for a `button` component having the `create` template.
 *
 * It is not recommended to modify this component, but if you will need to customize it, you will have to skip its generation via the `cli-config.json` file and `you will have to maintain it`:
 * https://wiki.vermeg.com/display/PFD/Workspace+Properties#WorkspaceProperties-F3
 */
@Injectable()
export class Button04826Action extends Action {}
